### ISSUE TITLE
 Property 'use:tippy' does not exist on type HTMLAttributes

### ISSUE THREAD

**Issue by b-des** [LXSMNSYC/solid-tippy#1]
Hello @LXSMNSYC. I want to use your bindings but I faced with TS compilation error:
`  Property 'use:tippy' does not exist on type 'HTMLAttributes<HTMLDivElement>'.`

Also I tried to use it as a hook, but it simply doesn't work - nothing happens.

Do you have any idea how to fix it?

**Comment by b-des** [comment]
Adding `//@ts-ignore` in JSX causes another error: tippy is not defined.
My code: 
![image](https://user-images.githubusercontent.com/14833882/174432484-57ef1439-5900-4de8-a2e0-f83c61fc36ce.png)

**Comment by lxsmnsyc** [comment]
Hi, thanks for reporting this issue. I forgot to mention on how directives are to be set up. You can follow this: https://www.solidjs.com/docs/latest/api#use%3A___

Then setup something like this:

```ts
import { TippyOptions } from 'solid-tippy';

declare module "solid-js" {
  namespace JSX {
    interface Directives {
      tippy: TippyOptions;
    }
  }
}
```

Another thing to note is that TypeScript doesn't understand directives, so it may remove the imports because it thinks that it is unused. However, you can do

```ts
import { tippy } from 'solid-tippy';
tippy; // emulate "usage"
```

**Comment by b-des** [comment]
Thank you for the answer. I've already managed. It's really tricky that TS removes imports which is used as a directives, it was bypassed by re-assigning the import to another constant
